### ISSUE TITLE
location

### ISSUE THREAD

**Issue by ivannunyadambiz** [patzly/grocy-android-unlock#1]
not available in switzerland. why?

**Comment by patzly** [comment]
@ivannunyadambiz Because I would be responsible for paying the tax to Switzerland. In (mostly) all other popular countries Google is responsible for doing this instead already, so developers don't have additional work. I wouldn't even know how to pay tax to another country, we are only 20 years old and the Internet is not very helpful regarding tax for online purchases...
That's why I disabled the app for Switzerland in the Google Play developer console and people like you can download it for free here on GitHub instead. If you would like to donate to us, you can find my PayPal account with my email address. Thanks for asking!
